default_platform :ios

platform :ios do

  before_all do
    puts "Doin' some fastlane..."
  end

  desc "Runs all the tests (debug and release)"
  lane :specs do
    scan(scheme: "SimpleOAuth2",
         clean: true,
         configuration: "Debug",
         output_style: "rspec")
  end

  after_all do |lane|
    if lane.equal? :test
      puts "🌮 🌮 🌮  Taco Time!  🌮 🌮 🌮"
    end
  end

  error do |lane, exception|
    puts "uh oh...."
  end

end
